#!/bin/bash
echo "🧪 Manual API Testing"
echo ""
echo "1. Start the server:"
echo "   cd backend && npm run dev"
echo ""
echo "2. In another terminal, test the endpoints:"
echo ""
echo "   # Health check"
echo "   curl http://localhost:3000/api/health"
echo ""
echo "   # Create reminder"
echo "   curl -X POST http://localhost:3000/api/reminders \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"text\":\"Test\",\"date\":\"2024-01-20\",\"time\":\"15:00\",\"userId\":123456789}'"
echo ""
echo "   # Get reminders"
echo "   curl 'http://localhost:3000/api/reminders?userId=123456789'"
